name: Wrangler Deploy to Production

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:

  deploy:

    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'prod'
