name: Wrangler CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

jobs:

  build-and-test:

    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.x'
      - name: Install
        run: |
          npm install -g @cloudflare/wrangler
          npm ci
      - name: Build
        run: |
          wrangler whoami
          wrangler build
      - name: Test
        run: |
          wrangler dev &
          sleep 10
          npm test

  deploy:
    needs: build-and-test
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Staging
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'staging'
